#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink 
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" 
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

NODE=${NODE-node}

if [ ! -d $DIR/node_modules ]; then
    echo "Installing prereqs for consolidator."
    npm install
    echo "Done."
fi

NODE_PATH=$NODE_PATH:$DIR/node_modules $NODE $DIR/consolidator.js "$@"
